### ISSUE TITLE
JEI's Cheat Mode

### ISSUE THREAD

**Issue by xermaa** [PlanetTeamSpeakk/MoreCommands#10]
![2020-03-15_15 01 25](https://user-images.githubusercontent.com/62199012/76697165-8b9f7200-66ce-11ea-8b3d-9a2f301314c4.png)

After I downloaded MoreCommands, when I try to toggle JEI's cheat mode, they always give me a message saying "You do not have permission to use JEI's Cheat Mode." I can only use it when i'm in creative mode. Even when I have /give perms, they still give the same message. Any ways to fix this?

**Comment by AcesGamingUK** [comment]
i too have this issue, 
[Report On JEI github](https://github.com/mezz/JustEnoughItems/issues/1999)

> So i recently added the mod [More Commands](https://www.curseforge.com/minecraft/mc-mods/morecommands)
> and now JEI cheatmode isn't working
> I ctrl-LClick the "wrench" and I instantly get a stack of NetherStars and the `you do not have permission to use....`
> Yes I have OP perms,
> Yes I can use the standalone /give
> 
> no it still wont work
> 
> [Vid](https://drive.google.com/file/d/1JPwAh781ExyoTnygXqA1z9emh6R6-dWW/view?usp=sharing)

**Comment by PlanetTeamSpeakk** [comment]
Will be looking into this soon, expect a new release of the mod for 1.12 (not 1.11, that's just too old by now) within a month.

**Comment by PlanetTeamSpeakk** [comment]
I have found out what causes the issue, thanks to you also reporting it to JEI and the owner of JEI responding with the code snippet that checks whether the command was successful.
It is because MoreCommands automatically makes commands be run on a separate thread as to not make the entire game freeze up when running commands that take a long time to process (e.g. /locate or /btp), but to prevent the command from running twice, the original event fired is cancelled which is how JEI determines if the command running was successful or not.

So what I'll do to fix it is just not run the /give command on a separate thread, this fix should work fine as long as JEI only checks permission for the give command which I presume it will.

Will be fixed in new version.

**Comment by Natedogwoooof** [comment]
not fixed

**Comment by gwynhefar** [comment]
I'm still having this issue too.  Will we get a fix at some point?  I really want to use this mod but I can't give up JEI
