### ISSUE TITLE
crash interacting with stairs

### ISSUE THREAD

**Issue by bheins** [PlanetTeamSpeakk/MoreCommands#28]
While right clicking with stairs there is a crash in the MoreCommands mod with the backtrace in the attached crash log
[crash_log.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6795339/crash_log.txt)

Mod list attached in log

**Comment by PlanetTeamSpeakk** [comment]
I'll be looking into this.

**Comment by PyjamallamaAU** [comment]
This is also an issue that I have also experienced with MoreCommands. Probably not required to post this but thought I should so that you know it is not just one person and you have an additional crash log, mods lists and computer specs being used so if needed you can try to replicate } CurseForge details and Mods list not computer specs as below/attached :) ] .

Using CurseForge App with options below -
MC Version: 1.17
Fabric Version: 0.11.6
Memory Assigned: 8GB

Base Hardware -
Processor: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz   3.50 GHz
Installed RAM: 32.0 GB (31.7 GB usable)
Video: nVidia GeForce GTX1050 Ti
HDD 1: Corsair Force GS 240GB SSD
HDD 2: Western Digital 3TB Red 3.5in SATA

Operation System -
Windows: 10 Pro 64-bit
Version: 21H1
OS build: 19043.1110


[1.17_Crash_Log.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6836282/1.17_Crash_Log.txt)
[1.17_Mod_List.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6836283/1.17_Mod_List.txt)

**Comment by PlanetTeamSpeakk** [comment]
This crash only seems to be happening in combination with Immersive Portals, I'll be looking into a fix later.

**Comment by bheins** [comment]
ok I'll get those tomorrow for you

**Comment by PyjamallamaAU** [comment]
Thanks for your response PTS - I think but cannot be 100% sure that I did not have immersive Portals installed initial when I found the issue however I will try removing it to test and let you know.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
