### ISSUE TITLE
When right-clicking on a block that has an GUI with a reach higher than 4.5 (/reach) GUI won't open

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#31]
When you set your reach to something higher than 4.5 (default), the GUI of a block that has an GUI won't open

**Comment by PlanetTeamSpeakk** [comment]
The actual issue is most likely when trying to open a block farther than 8 blocks away and this issue might be caused by mod incompatibilities. May I ask what mods you are running and what blocks you're trying to open? For the former, please refer to the latest.log in which it gets printed and not the files in your mods directory due to Fabric allowing mods to be loaded from mod jars.

**Comment by karstenzip** [comment]
[latest.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6834923/latest.log)
Is this good?

**Comment by PlanetTeamSpeakk** [comment]
What blocks did you try to open exactly?

**Comment by karstenzip** [comment]
Enchanting table, grindstone, anvil, barrel, chest, crafting table. None of them worked. I also just figured out, I can't mine blocks if the reach is higher and also no "use" them (like rightclicking on a button or lever). It's like I can't interact with them. It is only with blocks further than 8 blocks like you said.

**Comment by PlanetTeamSpeakk** [comment]
I actually fear that this is an incompatibility with Pehkui, or rather, a simple fix I implemented for incompatibility with Pehkui.
Normally with just Minecraft, Fabric, Fabric API, MoreCommands and maybe a couple other mods, this would work just fine, but Pehkui also modifies reach in the same way MoreCommands does this which makes them incompatible. To account for this, MoreCommands just doesn't modify the classes it needs to to fix this issue when Pehkui is loaded, or at least not all of them.
