### ISSUE TITLE
[Feature Request] Add permissions for gamerules

### ISSUE THREAD

**Issue by elhertz** [PlanetTeamSpeakk/MoreCommands#43]
[LuckPerms](https://www.curseforge.com/minecraft/mc-mods/luckperms)
or
[PlayerRoles](https://www.curseforge.com/minecraft/mc-mods/player-roles-fabric/)

With LuckPerms you need permission nodes (FabricPermissionsAPI), with PlayerRoles you can use those or give players access to a vanilla OP level (1, 2, 3, or 4).
It'd be nice to allow features such as "doItemColours" (gamerules) just for certain people.
You can currently limit the commands for certain players using PlayerRoles but having permission nodes for LuckPerms would be amazing.

**Comment by PlanetTeamSpeakk** [comment]
Permissions for commands using LuckPerms is already a thing and fully supported. Gamerules do not yet have permissions however. Not all gamerules can have permissions applied to them (e.g. hopper related ones) and others may be more useful in the case of a different value based on permissions (all integer gamerules like maxHomes and vaultRows), but boolean gamerules can definitely have permissions.
I'll probably implement this similar to how client options and disabling them works: if a client option is disabled by the server, the default value will be used on all clients of non-op players, otherwise the player may set it to any value they like. In this case, players with e.g. the permission for the maxHomes gamerule will be able to set for example 6 homes if the maxHomes gamerule is set to that and only 3 otherwise as that's the default value.
This may however form an issue with how things currently work and is definitely not ideal, but it's the easiest way to implement it for me. I may have to go with different values based on permissions, but I'm not sure how I'd end up doing that.

**Comment by elhertz** [comment]
> Permissions for commands using LuckPerms is already a thing and fully supported

Wow really? I couldn't find any info about this. Is there a list of permission nodes available?

Thank you for taking my request in consideration btw

**Comment by PlanetTeamSpeakk** [comment]
The permissions are really just `morecommands.` followed by the name of the command, but command autocompletion when typing something like `/lp group default permission set morecommands.` can help you out further.

**Comment by elhertz** [comment]
That's amazing! thanks

**Comment by PlanetTeamSpeakk** [comment]
Feature has been implemented for boolean rules, for now not planning on implementing this for integer rules as I cannot think of an elegant way of doing that.
