### ISSUE TITLE
1.19 non snapshot support?

### ISSUE THREAD

**Issue by srimanachanta** [PlanetTeamSpeakk/MoreCommands#69]
Could you rebuild binaries/jar for version 1.19 instead of snapshot 22w16b? There is no notable difference between the two versions so I belive it will be compatible.

**Comment by PlanetTeamSpeakk** [comment]
Sadly it's not that simple. Just because when playing you don't really see any difference, doesn't mean there are no differences. MoreCommands has a ton of mixins and any change in the code of the methods that it modifies will require modifying the mixin. This is one of the main reasons I update with snapshots, it makes the process more gradual instead of me having to work out lots of changes when a new stable release is dropped. I am already working on this, however, but I came across a bit of an issue with the new framework I'm using, Architectury, which has slowed the process down a bit.
The progress of this new version can be followed via the architectury branch on this repo though.

**Comment by PlanetTeamSpeakk** [comment]
This has now been done.
