### ISSUE TITLE
JustEnoughItems cheat mode no longer working Forge 1.12.2

### ISSUE THREAD

**Issue by SavageTheUnicorn** [PlanetTeamSpeakk/MoreCommands#81]
After creating the Operator group, adding perms to it with * and adding myself to the group, the JEI cheat mode no longer functions! It says that I don't have permission to use cheat mode, only players with access to /give or creative can access it, though I'm OP and in the Operator group already. HERE'S THE KICKER; It gives a single item(or stack) before reverting back to disabled and prompting the chat with said error. No output to console/errors produced. Can't find any bad logs either.

**Comment by SavageTheUnicorn** [comment]
Trying again today has slightly different results. Now instead of giving the proper item before automatically disabling and prompting the error, it give me a full stack of Nether Stars. Still says I need access to /give or creative, which I have full access to. Can't attach latest.log here anymore sadly.

**Comment by SavageTheUnicorn** [comment]
Switching to creative, enabling cheat mode, and switching back to survival gives the correct items but again, disables automatically with the error message.

**Comment by PlanetTeamSpeakk** [comment]
This is a known issue caused by MoreCommands making its commands run async to prevent lag, but in order for the commands to not run twice, the original event has to be cancelled. JEI sees this as the command failing to run and thus assumes you don't have permission to use cheat mode. Nothing I can do about this atm as 1.12 is too old of a version to still support.
